from __future__ import annotations

SCHEMA_VERSION = "1.0.0"
DEFAULT_DATASET_VERSION = "biosnap-dti-canonical-v1"
DEFAULT_SEEDS = (13, 29, 71)

DRUG_PREFIX = "DB"
PSEUDO_ENTITIES = frozenset({"#Drug", "Gene"})

MAX_SEARCH_RESULTS = 100
MAX_RECOMMENDATIONS = 100
MAX_PAIR_NODES = 150
MAX_PAIR_LINKS = 300
MAX_EGO_NODES = 250
MAX_EGO_LINKS = 600
MAX_EXPLANATION_PATHS = 5
